project:
  type: website
  resources:
    - assets/

license:
  type: "CC BY-NC"
  text: "CC BY-NC 4.0"
  link: "https://creativecommons.org/licenses/by-nc/4.0/"



format:
  revealjs:
    theme: [intertidalagency_theme.scss]
    css: custom.css
    slide-number: true
    incremental: false
    transition: none
    center: true
    footer: |
      Â© 2026 [Intertidal Agency](www.intertidalagency.org/) <a href="https://www.intertidalagency.org/" target="_blank"><img src="assets/Intertidal-ProfilePic-Aqua-Bold.png" style="height:30px; vertical-align:middle;"></a> License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
        


execute:
  freeze: auto
