project:
  type: website

format:
  revealjs:
    theme: simple
    css: theme.css
    slide-number: true
    incremental: false
    transition: fade
    center: true
    footer: |
      <img src="assets/the_data_patch_logo.png" style="height:60px; vertical-align:middle;"> www.thedatapatch.com

execute:
  freeze: auto
