project:
  type: website

license:
  type: "CC BY-NC"
  text: "CC BY-NC 4.0"
  link: "https://creativecommons.org/licenses/by-nc/4.0/"



format:
  revealjs:
    theme: simple
    css: [thedatapatch_theme.scss, custom.css]
    slide-number: true
    incremental: false
    transition: none
    center: true
    footer: |
      Â© 2026 [The Data Patch](https://www.thedatapatch.com) <a href="https://www.thedatapatch.com" target="_blank"><img src="assets/the_data_patch_logo.png" style="height:50px; vertical-align:middle;"></a> License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
        


execute:
  freeze: auto
